### ISSUE TITLE
Message omitting in message handlers

### ISSUE THREAD

**Issue by razenpok** [hadashiA/UniTaskPubSub#10]
It would be cool if you could pass a handler that doesn't actually use the message provided, i.e., when the message is just a signal without data.

```csharp
private void Awake()
{
    return AsyncMessageBus.Default.Subscribe<GameOverEvent>(FadeIn);
}

// Currently you must add `GameOverEvent gameOverEvent` argument or else it won't compile
private async UniTask FadeIn()
{
    // Stuff
}
```

**Comment by hadashiA** [comment]
Humm, While this may be useful in some cases, However, I prefer to have the callback be self-explanatory that it is a callback.

In your example, I think there is an option to make it go through a lambda expression, or to add arguments to the callback.

If you don't like those, please consider adding an extension method to IAsyncPublisher.
