### ISSUE TITLE
Really odd behaviour all of a sudden

### ISSUE THREAD

**Issue by Kevdome3000** [hadashiA/UniTaskPubSub#11]
Hey there,

First and foremost, thank you for your work! I'm a big fan of UniTask and this is a welcomed addition.

I've been running tests over the last couple of days and so far the results have been promising. But today I encountered some really odd behavior and after hours of trying to debug, I still can't figure it out. 

I have 3 tasks running asynchronously in the background that each publishes an event containing a task to be awaited for whichever subscribers care to know its status. 

`
class CustomEventMessage 
    {
        public UniTask Foo; 
    }
`

2 of the 3 tasks work as intended but the 3rd publishes its event and the event disappears into the ether, only to resurface after I exit play mode and the script assemblies have reloaded.

The subscriber has a debug.Log in its handler function to signify that the message was received, and the expected log message shows up in the console after the editor reloads. 

How can that be?

Any idea what could I be doing wrong?

Any help would be greatly appreciated!

**Comment by hadashiA** [comment]
Hi @Kevdome3000.  

I tried the following, but was unable to reproduce the problem.

```csharp
class CustomEventMessage { public UniTask Foo; }
```

```csharp
var i = 0;
AsyncMessageBus.Default.Subscribe<CustomEventMessage>(async msg =>
{
    i++;
    UnityEngine.Debug.Log($"Received! {i}");
    await msg.Foo;
    UnityEngine.Debug.Log($"Awaited! {i}");
});

await AsyncMessageBus.Default.PublishAsync(new CustomEventMessage
{
    Foo = UniTask.CompletedTask
});

await AsyncMessageBus.Default.PublishAsync(new CustomEventMessage
{
    Foo = UniTask.Delay(TimeSpan.FromSeconds(1f))
});

await AsyncMessageBus.Default.PublishAsync(new CustomEventMessage
{
    Foo = UniTask.Run(async () => await UniTask.Yield())
});

await AsyncMessageBus.Default.PublishAsync(new CustomEventMessage
{
    Foo = UniTask.Run(async () => await UniTask.Yield(PlayerLoopTiming.LastUpdate))
});
```

The log in my environment says "Awaited! 1" 〜 "Awaited! 4".
So, could you please provide some code to reproduce the problem? (Subscribe , Publish, etc.)

--

By the way, in my opinion, having UniTask as a property may cause some problems.
How about this?

- A UniTask can only be await once. But the public property can be await by anyone.
- The UniTask is executed as soon as it is created. If an exception is raised, the behavior would depend on the timing: if it is after the await, it would be supplemented as an exception in the method from which it was await; if it is before the await, it is the job of the global handler.
- Personally, I think it would be simpler if pub/sub messages are primitive data.

**Comment by Kevdome3000** [comment]
Thanks for getting back to me!

What I am trying to achieve is a GlobalMessageBroker that enables services to communicate without needing to be aware of each other - I guess the technical description is the Mediator Pattern?


My current setup looks something like this:

`

    public class MessageBroker
    {
        void OnEnable()
        {
            FooServiceClass.ServiceEvent += OnsServiceEvent;
            BarServiceClass.ServiceEvent += OnsServiceEvent;
        }
       
        public async void OnServiceEvent(UniTask task)
        {
            await AsyncMessageBus.Default.PublishAsync(new CustomEventMessage
            {
                Foo = task
            });
        }
    }
    
    
    public class FooServiceClass
    {
        public event Action<UniTask> ServiceEvent;
        
        
        void OnEnable()
        {
            SubscribeToMessageBroker().Forget();
        }
        
        private async UniTask SubscribeToMessageBroker()
        {
            AsyncMessageBus.Default.Subscribe<CustomEventMessage>(async (message) => await OnMessageBrokerMessage(message));
            await UniTask.Yield();
        }

        private async UniTask FooServiceFunction()
        {
        
        
            var task = UniTask.Create( async () =>
            {
                await task1;
                await task2;
                await task3;
                await task4;
            });
        
            ServiceEvent?.Invoke(task);
            
        }
        
        private async UniTask OnMessageBrokerMessage(CustomEventMessage message)
        {
            var task = message.Foo;
            (THE MESSAGE GETS LOST SOMEWHERE IN HERE AND DOESN'T EXECUTE IN PLAYMODE)
            task.GetAwaiter().OnCompleted(() =>
            {
                Debug.Log("Continuation task has started"); <= this Debug shows up in console after play mode has stopped
                await DOStuff();
            });
            
            await UniTask.Yield();
        }
    }
    
    

    public class BarServiceClass
    {
        
        public event Action<UniTask> ServiceEvent;
        
        void OnEnable()
        {
            SubscribeToMessageBroker().Forget();
        }
        
        private async UniTask SubscribeToMessageBroker()
        {
            AsyncMessageBus.Default.Subscribe<CustomEventMessage>(async (message) => await OnMessageBrokerMessage(message));
            await UniTask.Yield();
        }
        
        
        private async UniTask BarServiceFunction()
        {
            var task = UniTask.Create( async () =>
            {
                await task1;
                await task2;
                await task3;
                await task4;
            });
        
            ServiceEvent?.Invoke(task);
            
        }
        
        private async UniTask OnMessageBrokerMessage(CustomEventMessage message)
        {
            var task = message.Foo;

            task.GetAwaiter().OnCompleted(() =>
            {
                await DOStuff();
            });
            
            await UniTask.Yield();
        }
    }
` 

The problem I'm trying to solve is keeping the UI in sync with the background tasks, especially in the case of a new player sign up. I'm not sure how long a new user will take to get through the signup flow, but there are background tasks that need to finish before the initial game view is displayed. I need to be able to know on the UI thread if all tasks are completed or not, so in the case that they aren't, I can show a loading animation.

I know this is a problem all game devs face but I couldn't find any concrete examples of how to implement with UniTask. If you have any comments on best practices to handle this scenario, I'm all ears :)

Regarding the approach you suggested, I'm not sure I follow completely. 

Could you provide an example of implementation?

Thanks in advance for taking the time to help

**Comment by hadashiA** [comment]
@Kevdome3000 In short, Why do you need to use `GetAwaiter()` ?
awaiter's OnCompleted is usually called by code automatically generated by the compiler.
If you want to do something after the UniTask completes, use await; if you can't, use ContinueWith.

( Also, `.OnCompleted(async () => await DOStuff())` This lambda expression does not create a UniTask, it is an async void. )

And, I would also like to point out a few things about your MessageBroker code.

- I still don't think that messages should have UniTask. In the pub/sub pattern, we leave it to the subscriber to decide how to process the message. The message should be primitive data and separated from the logic.
- In my opinion, AsyncMessageBus itself is already a Message Broker :)  


Why don't you use the following structure?

```csharp
messageBus.Subscribe<FooMessage>(async msg => await fooService.FooAsync(msg))
messageBus.Subscribe<BarMessage>(async msg => await barService.BarAsync(msg))
```

I have not done any detailed debugging, but I have determined that this case is not a UniTaskPubSub problem.

If it seems to be a bug in UniTaskPubSub, please report back.
