### ISSUE TITLE
Missing support of UniTaskVoid

### ISSUE THREAD

**Issue by razenpok** [hadashiA/UniTaskPubSub#9]
`AsyncMessageBus` subscription methods don't accept `Func<T, UniTaskVoid>` arguments which cut short `AsyncMessageBus`+`UniTaskVoid` usage scenarios

```csharp
private void Awake()
{
    return AsyncMessageBus.Default.Subscribe<GameOverEvent>(FadeIn);
}

private async UniTaskVoid FadeIn(GameOverEvent gameOverEvent)
{
    // Stuff
}
```

**Comment by hadashiA** [comment]
Hello. Why do we force UniTaskVoid?
When implementing event handlers, there should be no difference between UniTask and UniTaskVoid.

Handlers registered in AsyncMessageBus can use both await and try/catch. Therefore, UniTask seems to be appropriate instead of UniTaskVoid (like async void).

**Comment by razenpok** [comment]
Fair enough, didn't think about it this way. Probably worth it explaining in the readme.
